<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/slimdraig/image/upload/v1554329829/Snapchat-25245111_Cropped.jpg" alt="Azeez Sunday">
                        <h6>Azeez Sunday`</h6>
                        <p>UI/UX DESIGNER</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/mvo_arisekola" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/slimdraig" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@azeezsunday.a" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Azeez Sunday Arisekola, a 3rd year student of cybersecurity at The Univerity of Technology, Akure. I have basic knowledge on most programming languages i've done in school including PHP, PYTHON, & JAVA. I'm a self tutored newbie on UI/UX design using figma and very trainable</p>
                        <br />
                        <h6>Skills</h6>
                        <p>FIGMA | PHP | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
